### ISSUE TITLE
Sign-in issue

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/Feedback#94]
This issue is to report an issue with signing in and out. Specifically, I signed into qgraph under my Copperline email and then decided to switch to my RENCI email. However, I can't seem to "switch accounts" or simply log out and log in again.

**Comment by cbizon** [comment]
@karafecho I suspect that this is fixed?  Please reopen if I am wrong

**Comment by karafecho** [comment]
Issue not resolved. I still can't log out after signing in (404 error).

**Comment by karafecho** [comment]
Update: I can log out successfully; just needed to manually refresh my browser. I think there are still minor browser issues, but we can close this ticket for now.
